title: Material de Estudio
lang: es
author:
  name: Centro de Estudiantes - FICH
  email: un@correo.com

description: ""
logo: favicon.ico

baseurl: ""
url: "https://estudios.ceich.tk"

minima:
  skin: classic
  social_links:
    facebook: mnr.fich
    instagram: mnrfich

disqus:
  shortname: ceich-mde

google_analytics: UA-160835896-1

# Build settings
# theme: minima

header_pages:
  - archivos.md

plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
  -
    scope:
      path: ""
    values:
      image: favicon.ico
